# Generated by Django 3.0 on 2021-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('alternative_title', models.TextField()),
                ('category', models.CharField(choices=[('anime', 'Anime'), ('cartoon', 'Cartoon'), ('manga', 'Manga'), ('comic', 'Comic'), ('live action', 'Live action')], max_length=100)),
                ('production', models.CharField(default='multiple', max_length=300)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('relation', models.CharField(choices=[('original', 'Original'), ('series', 'Series'), ('movie', 'Movie'), ('alternative', 'Alternative'), ('ova', 'OVA')], default='original', max_length=200)),
                ('parent', models.CharField(max_length=200)),
                ('profile_pic', models.TextField()),
            ],
        ),
    ]
