# Generated by Django 3.0 on 2022-01-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_film_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='order',
        ),
    ]
