# Generated by Django 3.0 on 2022-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0004_remove_film_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
