# Generated by Django 3.0 on 2022-01-09 11:01

import Films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0005_film_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('UPCOMING', 'UPCOMING'), ('FINISHED', 'FINISHED')], default='ONGOING', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('cartoon', 'Cartoon'), ('manga', 'Manga'), ('comic', 'Comic'), ('live action', 'Live action')], default='anime', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[Films.models.valid_rating]),
        ),
    ]
