# Generated by Django 3.0 on 2022-01-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_auto_20220109_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Contents',
            field=models.CharField(choices=[('original', 'Original'), ('series', 'Series'), ('movie', 'Movie'), ('alternative', 'Alternative'), ('ova', 'OVA'), ('new', 'new'), ('fds', 'fdf')], default='original', max_length=200),
        ),
    ]
