# Generated by Django 3.0 on 2022-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0007_auto_20220109_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='profile_pic',
            field=models.TextField(default='image/400097700330_82090.jpg'),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('UPCOMING', 'UPCOMING'), ('FINISHED', 'FINISHED'), ('PLANNED', 'PLANNED'), ('HELLO', 'HELLO'), ('WELCOME', 'WELCOME')], default='ONGOING', max_length=255),
        ),
    ]
