# Generated by Django 3.0 on 2021-12-27 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('watch list', 'WATCH LIST'), ('complete', 'COMPLETE'), ('watching', 'watching')], max_length=100)),
                ('current', models.IntegerField()),
                ('Local', models.TextField(max_length=200)),
                ('registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Films.Film')),
            ],
        ),
    ]
